files:
- generatedChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
  logicalPath: config/DSP_TU
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
- generatedChecksum: 7B902CE810096FC4DC858B327D0163B7
  logicalPath: config/DSP_TU
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 631B83FA8198B09E264D43A93291F8F6
- generatedChecksum: A9FBF5CF9B42BB62511ADC41DAF8CA91
  logicalPath: config/DSP_TU
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: A9FBF5CF9B42BB62511ADC41DAF8CA91
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 5EEA657806D85ED4AF8AA11384F3D575
  logicalPath: config/DSP_TU/peripheral/adchs
  name: plib_adchs.c
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5EEA657806D85ED4AF8AA11384F3D575
- generatedChecksum: 2E247749DAFCDC08BE03DACF917FDA76
  logicalPath: config/DSP_TU/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2E247749DAFCDC08BE03DACF917FDA76
- generatedChecksum: 128254EF0582484C353550278B2DB93A
  logicalPath: config/DSP_TU/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 128254EF0582484C353550278B2DB93A
- generatedChecksum: 113B18B76E859EB9AE4158904598C659
  logicalPath: config/DSP_TU/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 113B18B76E859EB9AE4158904598C659
- generatedChecksum: BB7545FB502999A8F19893F95ADE53D6
  logicalPath: config/DSP_TU/peripheral/ocmp
  name: plib_ocmp1.c
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: SOURCE
  userChecksum: BB7545FB502999A8F19893F95ADE53D6
- generatedChecksum: D2C1A30244672B2F57B982CD898DF6DF
  logicalPath: config/DSP_TU/peripheral/spi/spi_master
  name: plib_spi1_master.c
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: D2C1A30244672B2F57B982CD898DF6DF
- generatedChecksum: CB7A5E17457F3268C31238F6CA69E413
  logicalPath: config/DSP_TU/peripheral/tmr
  name: plib_tmr2.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 993950AF4B155F413F2CBC6292849AF5
- generatedChecksum: 58F2EE9A387D51AA613CBADBFE89EF6D
  logicalPath: config/DSP_TU/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 58F2EE9A387D51AA613CBADBFE89EF6D
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/DSP_TU/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: 73BA1EC72E1D71DED686867FB42913EA
  logicalPath: config/DSP_TU
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 73BA1EC72E1D71DED686867FB42913EA
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/DSP_TU
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/DSP_TU
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: B2EE65C30069B4D8072900E7D5C17151
  logicalPath: config/DSP_TU/peripheral/adchs
  name: plib_adchs.h
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: B2EE65C30069B4D8072900E7D5C17151
- generatedChecksum: 8B9CC19AAA7FCCE989C0D0CF678E7AD3
  logicalPath: config/DSP_TU/peripheral/adchs
  name: plib_adchs_common.h
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: 8B9CC19AAA7FCCE989C0D0CF678E7AD3
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/DSP_TU/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: C8175D686FECDA56EC0FED1578D4ECA7
  logicalPath: config/DSP_TU/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: C8175D686FECDA56EC0FED1578D4ECA7
- generatedChecksum: 5841979741C4B9127E185AD395830B38
  logicalPath: config/DSP_TU/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 5841979741C4B9127E185AD395830B38
- generatedChecksum: 6CEA8203317C87CCE71D84E419A2B434
  logicalPath: config/DSP_TU/peripheral/ocmp
  name: plib_ocmp1.h
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: 6CEA8203317C87CCE71D84E419A2B434
- generatedChecksum: C7376B9C0FE98B35880E7395A16846B2
  logicalPath: config/DSP_TU/peripheral/ocmp
  name: plib_ocmp_common.h
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: C7376B9C0FE98B35880E7395A16846B2
- generatedChecksum: 27EFFF00EA5DD882C446A714F0D9CE9E
  logicalPath: config/DSP_TU/peripheral/spi/spi_master
  name: plib_spi1_master.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: 27EFFF00EA5DD882C446A714F0D9CE9E
- generatedChecksum: CFA758C8B7258190473EF7C60C4BA4E9
  logicalPath: config/DSP_TU/peripheral/spi/spi_master
  name: plib_spi_master_common.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: CFA758C8B7258190473EF7C60C4BA4E9
- generatedChecksum: 612994C7F3C27F2CFA2621C1F65D4068
  logicalPath: config/DSP_TU/peripheral/tmr
  name: plib_tmr2.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 612994C7F3C27F2CFA2621C1F65D4068
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config/DSP_TU/peripheral/tmr
  name: plib_tmr_common.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: 9042B36EACA99ACB163ED84CD9969944
  logicalPath: config/DSP_TU/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 9042B36EACA99ACB163ED84CD9969944
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config/DSP_TU/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: CAC44960D20AEC03CF4B325A1CD2877C
  logicalPath: config/DSP_TU
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CAC44960D20AEC03CF4B325A1CD2877C
- generatedChecksum: AEF7EF01AC9845EDF7A4B894D7581863
  logicalPath: config/DSP_TU
  name: p32MZ2048EFM100.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: AEF7EF01AC9845EDF7A4B894D7581863
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/DSP_TU;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/DSP_TU;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
